title: Gnawave Project
description: Bridging Moroccan Gnawa music traditions with contemporary artificial intelligence research.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: gnawave_project
github_username:  pollinations

# Build settings
markdown: kramdown
remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-remote-theme pdated theme for a modern and visually appealing look
  - jekyll-feed
  - jekyll-seo-tag # Added for better SEO

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/