title: Gnawave Project
baseurl: /
url: https://pollinations.github.io/Gnawave/
description: Bridging Moroccan Gnawa music traditions with contemporary artificial intelligence research.
show_downloads: false
github_username:  pollinations
logo: /media/GnaouaCultureLogo.png
# Build settings
theme: jekyll-theme-hacker
plugins:
#  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag # Added for better SEO

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/