source 'https://rubygems.org'
gem 'jekyll', '~> 4.2.0'
gem 'jekyll-theme-hacker'
gem 'jekyll-feed'
gem 'webrick'
gem 'jekyll-theme-minimal'
gem 'jekyll-theme-leap-day'
gem 'jekyll-theme-slate'
gem 'jekyll-theme-tactile'

